spring.application.name=StudentManagementSystem


spring.datasource.url=jdbc:mysql://localhost:3306/student
spring.datasource.username=root
spring.datasource.password=vivek@1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.First.StudentManagementSystem=DEBUG
jwt.secret=bci32nfn+fmhwkfjsbsj1njsbnvbckebDekvnhg6fehsfnjeh=
jwt.expiration=86400000